spring:
  application:
    name: ActivityService
  data:
    mongodb:
      uri: mongodb://localhost:27017/aiActivityFitness
#      database: aiActivityFitness

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082